import { formatUsd } from "../../domain/money.js";
import type { InvestigationRecord } from "../../agent/types.js";
import { ConfidenceBadge } from "../StatusBadge.js";

function Facts({ investigation }: { investigation: InvestigationRecord }) {
  const f = investigation.facts;
  const rows: [string, string][] = [];

  if (f.comparison_total_cents !== null && f.current_total_cents !== null) {
    rows.push([
      `${investigation.comparisonPeriod} total`,
      formatUsd(f.comparison_total_cents)
    ]);
    rows.push([
      `${investigation.currentPeriod} total`,
      formatUsd(f.current_total_cents)
    ]);
  }
  if (f.variance_cents !== null) {
    rows.push([
      "Variance",
      `${formatUsd(f.variance_cents)}${
        f.percentage_variance_display === null
          ? ""
          : ` (${f.percentage_variance_display}%)`
      }`
    ]);
  }
  if (f.price_changed !== null) {
    rows.push(["Price changed", f.price_changed ? "yes" : "no"]);
  }
  if (f.change_date) rows.push(["Usage change date", f.change_date]);
  if (f.correlated_event_id) {
    rows.push(["Correlated event", f.correlated_event_id]);
  }
  if (f.exact_duplicate_count !== null) {
    rows.push([
      "Duplicates",
      `${f.exact_duplicate_count} exact, ${f.probable_duplicate_count} probable`
    ]);
  }
  if (f.reconciliation_status) {
    rows.push(["Reconciliation", f.reconciliation_status]);
  }
  if (f.explained_percent !== null) {
    rows.push(["Variance explained", `${f.explained_percent.toFixed(2)}%`]);
  }

  if (rows.length === 0) return null;

  return (
    <dl className="facts">
      {rows.map(([label, value]) => (
        <div key={label}>
          <dt>{label}</dt>
          <dd>{value}</dd>
        </div>
      ))}
    </dl>
  );
}

export function SummaryTab({
  investigation
}: {
  investigation: InvestigationRecord | null;
}) {
  if (!investigation) {
    return (
      <p className="panel-empty">
        The conclusion, its confidence and the recommended next step appear here.
      </p>
    );
  }

  if (investigation.state === "clarification_required") {
    return (
      <div className="summary summary--clarify" role="status">
        <h3>More detail needed</h3>
        <p>{investigation.clarificationQuestion}</p>
      </div>
    );
  }

  const summary = investigation.summary;
  if (!summary) {
    return <p className="panel-empty">The investigation has not concluded yet.</p>;
  }

  const unresolved = !summary.invoiceAppearsCorrect;

  return (
    <div className={`summary ${unresolved ? "summary--unresolved" : ""}`}>
      <div className="summary__head">
        <h3>{unresolved ? "Unresolved" : "Invoice appears correct"}</h3>
        <ConfidenceBadge confidence={investigation.facts.confidence} />
      </div>

      <p className="summary__finding">{summary.finding}</p>

      <Facts investigation={investigation} />

      {summary.evidence.length > 0 && (
        <>
          <h4>Evidence</h4>
          <ul className="summary__evidence">
            {summary.evidence.map((line) => (
              <li key={line}>{line}</li>
            ))}
          </ul>
        </>
      )}

      <h4>Assessment</h4>
      <p>{summary.assessment}</p>

      {investigation.blockers.length > 0 && (
        <>
          <h4>Outstanding</h4>
          <ul className="summary__blockers">
            {investigation.blockers.map((b) => (
              <li key={b}>{b}</li>
            ))}
          </ul>
        </>
      )}

      <h4>Recommended next step</h4>
      <p>{summary.recommendedNextStep}</p>

      <p className="summary__provenance">
        {/* Worth surfacing: it tells the reader whether an LLM phrased this. */}
        {summary.generatedBy === "model"
          ? "Wording generated by the model from verified figures."
          : "Wording generated deterministically from verified figures."}{" "}
        {investigation.metrics.toolCalls} tool calls ·{" "}
        {investigation.metrics.planningCycles} planning cycles.
      </p>
    </div>
  );
}
