import type { BillingDataset } from "../src/domain/types.js";

type Value = string | number | null;

function literal(value: Value): string {
  if (value === null) return "NULL";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`non-finite value: ${value}`);
    return String(value);
  }
  return `'${value.replace(/'/g, "''")}'`;
}

/** Multi-row INSERTs, batched so a seed run is a few dozen statements. */
function insertRows(
  table: string,
  columns: string[],
  rows: Value[][],
  batchSize = 200
): string[] {
  const statements: string[] = [];
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const values = batch
      .map((row) => `  (${row.map(literal).join(", ")})`)
      .join(",\n");
    statements.push(
      `INSERT OR REPLACE INTO ${table} (${columns.join(", ")}) VALUES\n${values};`
    );
  }
  return statements;
}

/**
 * Deletion order is the reverse of insertion so foreign keys stay satisfied,
 * which is what makes re-seeding a populated database safe.
 */
const TABLES_IN_DEPENDENCY_ORDER = [
  "invoice_lines",
  "invoices",
  "rated_charges",
  "daily_usage",
  "usage_events",
  "account_events",
  "price_versions",
  "subscriptions",
  "zones",
  "accounts"
];

export function emitSql(dataset: BillingDataset): string {
  const parts: string[] = [
    "-- Generated by seed/run.ts. Do not edit by hand.",
    "-- All customer, contract, pricing, usage, and invoice data is synthetic.",
    ""
  ];

  for (const table of TABLES_IN_DEPENDENCY_ORDER) {
    parts.push(`DELETE FROM ${table};`);
  }
  parts.push("");

  parts.push(
    ...insertRows(
      "accounts",
      [
        "account_id",
        "display_name",
        "plan_type",
        "currency",
        "tax_status",
        "primary_zone_id",
        "primary_zone_name",
        "is_synthetic"
      ],
      [
        [
          dataset.account.accountId,
          dataset.account.displayName,
          dataset.account.planType,
          dataset.account.currency,
          dataset.account.taxStatus,
          dataset.account.primaryZoneId,
          dataset.account.primaryZoneName,
          1
        ]
      ]
    )
  );

  parts.push(
    ...insertRows(
      "zones",
      ["zone_id", "account_id", "zone_name"],
      dataset.zones.map((z) => [z.zoneId, z.accountId, z.zoneName])
    )
  );

  parts.push(
    ...insertRows(
      "subscriptions",
      [
        "subscription_id",
        "account_id",
        "plan_name",
        "monthly_fee_cents",
        "started_on",
        "ended_on"
      ],
      dataset.subscriptions.map((s) => [
        s.subscriptionId,
        s.accountId,
        s.planName,
        s.monthlyFeeCents,
        s.startedOn,
        s.endedOn
      ])
    )
  );

  parts.push(
    ...insertRows(
      "price_versions",
      [
        "price_version_id",
        "account_id",
        "service_name",
        "service_family",
        "included_quantity",
        "overage_rate_cents",
        "unit_divisor",
        "unit",
        "fixed_fee_cents",
        "effective_from",
        "effective_to"
      ],
      dataset.priceVersions.map((p) => [
        p.priceVersionId,
        p.accountId,
        p.serviceName,
        p.serviceFamily,
        p.includedQuantity,
        p.overageRateCents,
        p.unitDivisor,
        p.unit,
        p.fixedFeeCents,
        p.effectiveFrom,
        p.effectiveTo
      ])
    )
  );

  parts.push(
    ...insertRows(
      "usage_events",
      [
        "event_id",
        "account_id",
        "service_name",
        "zone_id",
        "source_event_key",
        "occurred_at",
        "quantity",
        "unit"
      ],
      dataset.usageEvents.map((e) => [
        e.eventId,
        e.accountId,
        e.serviceName,
        e.zoneId,
        e.sourceEventKey,
        e.occurredAt,
        e.quantity,
        e.unit
      ])
    )
  );

  parts.push(
    ...insertRows(
      "daily_usage",
      [
        "account_id",
        "service_name",
        "zone_id",
        "usage_date",
        "quantity",
        "unit",
        "source_event_count",
        "source_event_first",
        "source_event_last"
      ],
      dataset.dailyUsage.map((d) => [
        d.accountId,
        d.serviceName,
        d.zoneId,
        d.usageDate,
        d.quantity,
        d.unit,
        d.sourceEventCount,
        d.sourceEventFirst,
        d.sourceEventLast
      ])
    )
  );

  parts.push(
    ...insertRows(
      "rated_charges",
      [
        "rated_charge_id",
        "account_id",
        "service_name",
        "period",
        "consumed_quantity",
        "included_quantity",
        "billable_quantity",
        "price_version_id",
        "amount_cents"
      ],
      dataset.ratedCharges.map((r) => [
        r.ratedChargeId,
        r.accountId,
        r.serviceName,
        r.period,
        r.consumedQuantity,
        r.includedQuantity,
        r.billableQuantity,
        r.priceVersionId,
        r.amountCents
      ])
    )
  );

  parts.push(
    ...insertRows(
      "invoices",
      [
        "invoice_id",
        "account_id",
        "period",
        "status",
        "currency",
        "subtotal_cents",
        "credit_cents",
        "tax_cents",
        "total_cents",
        "issued_on"
      ],
      dataset.invoices.map((i) => [
        i.invoiceId,
        i.accountId,
        i.period,
        i.status,
        i.currency,
        i.subtotalCents,
        i.creditCents,
        i.taxCents,
        i.totalCents,
        i.issuedOn
      ])
    )
  );

  parts.push(
    ...insertRows(
      "invoice_lines",
      [
        "line_id",
        "invoice_id",
        "account_id",
        "service_name",
        "line_type",
        "quantity",
        "amount_cents",
        "rated_charge_id",
        "subscription_id"
      ],
      dataset.invoiceLines.map((l) => [
        l.lineId,
        l.invoiceId,
        l.accountId,
        l.serviceName,
        l.lineType,
        l.quantity,
        l.amountCents,
        l.ratedChargeId,
        l.subscriptionId
      ])
    )
  );

  parts.push(
    ...insertRows(
      "account_events",
      [
        "event_id",
        "account_id",
        "event_type",
        "name",
        "zone_id",
        "occurred_at",
        "metadata"
      ],
      dataset.accountEvents.map((e) => [
        e.eventId,
        e.accountId,
        e.eventType,
        e.name,
        e.zoneId,
        e.occurredAt,
        e.metadata
      ])
    )
  );

  return `${parts.join("\n")}\n`;
}
